id = "tokyo-black"
name = "Tokyo Black Themes"
version = "0.1.0"
schema_version = 1
authors = ["azzamsa <noreply@azzamsa.com>"]
description = "Tokyo Black Themes"
repository = "https://github.com/azzamsa/tokyo-black.zed"
