name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    environment: release
    steps:

      - uses: huacnlee/zed-extension-action@latest
        with:
          extension-name: tokyo-black-themes
          push-to: azzamsa/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
